"""Add pre_leads table

Revision ID: 09c33a7a68d1
Revises: 3cb2f388cd42
Create Date: 2025-06-06 11:59:26.955520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c33a7a68d1'
down_revision: Union[str, None] = '3cb2f388cd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_lead_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_leads_id'), 'pre_leads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_leads_id'), table_name='pre_leads')
    op.drop_table('pre_leads')
    # ### end Alembic commands ###
