"""Fix user location fields

Revision ID: 765b4261b690
Revises: 5b44381e0599
Create Date: 2025-05-30 22:30:42.457225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '765b4261b690'
down_revision: Union[str, None] = '5b44381e0599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    op.drop_column('users', 'current_lat')
    op.drop_column('users', 'last_checkin')
    op.drop_column('users', 'current_lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_checkin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_location_update')
    op.drop_column('users', 'current_longitude')
    op.drop_column('users', 'current_latitude')
    # ### end Alembic commands ###
