"""Fix lead location fields and add estimated_value

Revision ID: 7c107bd9796d
Revises: 765b4261b690
Create Date: 2025-05-30 22:32:30.644209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c107bd9796d'
down_revision: Union[str, None] = '765b4261b690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('leads', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('leads', sa.Column('estimated_value', sa.Float(), nullable=True))
    op.drop_column('leads', 'lat')
    op.drop_column('leads', 'lng')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('leads', 'estimated_value')
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    # ### end Alembic commands ###
